workflows:
  react-native-android:
    name: Android Build
    max_build_duration: 60

    environment:
      node: 18
      java: 11

    scripts:
      - npm install
      - npx react-native build-android --variant=release

    artifacts:
      - android/app/build/outputs/**/*.apk
